#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: phpize
# autospec version: v3
# autospec commit: c1050fe
#
Name     : php-Bitset
Version  : 3.2.0
Release  : 74
URL      : https://pecl.php.net/get/bitset-3.2.0.tgz
Source0  : https://pecl.php.net/get/bitset-3.2.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-Bitset-lib = %{version}-%{release}
Requires: php-Bitset-license = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : perl(Getopt::Long)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
BITSET
Released under the PHP License 3.01
The BitSet extension assists by providing a mechanism to manage sets of bits.
This provides a similar API (object-based) to java.util.BitSet with some
PHP-specific flavoring.

%package lib
Summary: lib components for the php-Bitset package.
Group: Libraries
Requires: php-Bitset-license = %{version}-%{release}

%description lib
lib components for the php-Bitset package.


%package license
Summary: license components for the php-Bitset package.
Group: Default

%description license
license components for the php-Bitset package.


%prep
%setup -q -n bitset-3.2.0
cd %{_builddir}/bitset-3.2.0
pushd ..
cp -a bitset-3.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-Bitset
cp %{_builddir}/bitset-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-Bitset/23cb6fa873d559515b754db54720962118c95899 || :
%make_install

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20230831/bitset.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/php-Bitset/23cb6fa873d559515b754db54720962118c95899
