#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-Bitset
Version  : 3.0.1
Release  : 36
URL      : https://pecl.php.net//get/bitset-3.0.1.tgz
Source0  : https://pecl.php.net//get/bitset-3.0.1.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-Bitset-lib = %{version}-%{release}
Requires: php-Bitset-license = %{version}-%{release}
BuildRequires : buildreq-php

%description
BITSET
Released under the PHP License 3.01
The BitSet library assists by providing a mechanism to manage sets of bits. This
provides a similar API (object-based) to java.util.BitSet with some PHP-specific
flavoring.

%package lib
Summary: lib components for the php-Bitset package.
Group: Libraries
Requires: php-Bitset-license = %{version}-%{release}

%description lib
lib components for the php-Bitset package.


%package license
Summary: license components for the php-Bitset package.
Group: Default

%description license
license components for the php-Bitset package.


%prep
%setup -q -n bitset-3.0.1
cd %{_builddir}/bitset-3.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-Bitset
cp %{_builddir}/bitset-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-Bitset/23cb6fa873d559515b754db54720962118c95899
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20220829/bitset.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/php-Bitset/23cb6fa873d559515b754db54720962118c95899
